"""new tables

Revision ID: b52af171bd27
Revises: 
Create Date: 2023-01-18 15:17:59.492548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52af171bd27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('TotalSocialInvestment', sa.Float(), nullable=True),
    sa.Column('TotalEnergyGenerated', sa.Float(), nullable=True),
    sa.Column('TotalNonFossilFuelEnergyGenerated', sa.Float(), nullable=True),
    sa.Column('DirectGHGEmissions', sa.Float(), nullable=True),
    sa.Column('IndirectGHGEmissions', sa.Float(), nullable=True),
    sa.Column('EmissionsNeutralizedbyCarbonOffsetProjects', sa.Float(), nullable=True),
    sa.Column('EmissionsOfODS', sa.Float(), nullable=True),
    sa.Column('EmissionsOfNOX', sa.Float(), nullable=True),
    sa.Column('EmissionsOfSOX', sa.Float(), nullable=True),
    sa.Column('WaterWithdrawal', sa.Float(), nullable=True),
    sa.Column('FreshWaterDischarge', sa.Float(), nullable=True),
    sa.Column('OtherWaterDischarge', sa.Float(), nullable=True),
    sa.Column('WaterRecycled', sa.Float(), nullable=True),
    sa.Column('WasteGeneratedHazardous', sa.Float(), nullable=True),
    sa.Column('WasteGeneratedNonHazardous', sa.Float(), nullable=True),
    sa.Column('DivertedWaste', sa.Float(), nullable=True),
    sa.Column('EnvironmentalFines', sa.Float(), nullable=True),
    sa.Column('FlaredHydrocarbon', sa.Float(), nullable=True),
    sa.Column('VentedHydrocarbon', sa.Float(), nullable=True),
    sa.Column('calc1', sa.Float(), nullable=True),
    sa.Column('calc2', sa.Float(), nullable=True),
    sa.Column('calc3', sa.Float(), nullable=True),
    sa.Column('calc4', sa.Float(), nullable=True),
    sa.Column('calc5', sa.Float(), nullable=True),
    sa.Column('calc6', sa.Float(), nullable=True),
    sa.Column('calc7', sa.Float(), nullable=True),
    sa.Column('calc8', sa.Float(), nullable=True),
    sa.Column('calc9', sa.Float(), nullable=True),
    sa.Column('calc10', sa.Float(), nullable=True),
    sa.Column('calc11', sa.Float(), nullable=True),
    sa.Column('calc12', sa.Float(), nullable=True),
    sa.Column('calc13', sa.Float(), nullable=True),
    sa.Column('calc14', sa.Float(), nullable=True),
    sa.Column('calc15', sa.Float(), nullable=True),
    sa.Column('calc16', sa.Float(), nullable=True),
    sa.Column('calc17', sa.Float(), nullable=True),
    sa.Column('calc18', sa.Float(), nullable=True),
    sa.Column('calc19', sa.Float(), nullable=True),
    sa.Column('calc20', sa.Float(), nullable=True),
    sa.Column('calc21', sa.Float(), nullable=True),
    sa.Column('calc22', sa.Float(), nullable=True),
    sa.Column('calc23', sa.Float(), nullable=True),
    sa.Column('calc24', sa.Float(), nullable=True),
    sa.Column('calc25', sa.Float(), nullable=True),
    sa.Column('calc26', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('energy')
    # ### end Alembic commands ###
